### ISSUE TITLE
CRITICAL

### ISSUE THREAD

**Issue by dinohromic** [QodeMaster/TDA553-lab1#4]
Hej, jag märker att ni inte rättat till de saker jag bett er göra ännu. Jag har försökt komma i kontakt med er men inte lyckats. Rätta till de felen jag skrivit. Sen gör snälla en tag för labb 2 så att jag vet vilken kod det är ni skulle vilja ha rättad för den också.
Mvh // Dino Hromic [TA]

**Comment by dinohromic** [comment]
Detta är alltså gällande labb 1. Vill helst att ni rättar till de små sakerna så jag kan börja rätta er andra labb.

**Comment by QodeMaster** [comment]
Ok vi har gjort ändringarna.
